### ISSUE TITLE
Can't get it to work with ollama

### ISSUE THREAD

**Issue by jamieduk** [ErikBjare/gptme#176]
shoddy asf fixit! i expect this to work with local ollama out of the box again fixit!

<details><summary>
 gptme --model local/crewai-llama2-uncensored "hello"
</summary>
WARNING:gptme.models:Unknown model crewai-llama2-uncensored, using fallback metadata
[23:43:58] Using logdir ~/.local/share/gptme/logs/2024-10-08-walking-pink-bird  
           Using workspace at ~/Documents/Scripts/AI/gptme-ai                   
           Using project configuration at                                       
           ~/Documents/Scripts/AI/gptme-ai/gptme.toml                           
Skipped 2 hidden system messages, show with --show-hidden
--- ^^^ past messages ^^^ ---
User: hello
INFO:openai._base_client:Retrying request to /chat/completions in 0.409328 seconds
INFO:openai._base_client:Retrying request to /chat/completions in 0.802017 seconds
Traceback (most recent call last):                                              
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/openai/_base_client.py", line 990, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jay/.local/bin/gptme", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/gptme/cli.py", line 224, in main
    chat(
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/gptme/chat.py", line 110, in chat
    response_msgs = list(step(log, no_confirm, stream=stream))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/gptme/chat.py", line 192, in step
    msg_response = reply(msgs, get_model().model, stream)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/gptme/llm.py", line 47, in reply
    return _reply_stream(messages, model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/gptme/llm.py", line 84, in _reply_stream
    for char in (char for chunk in _stream(messages, model) for char in chunk):
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/gptme/llm.py", line 84, in <genexpr>
    for char in (char for chunk in _stream(messages, model) for char in chunk):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/gptme/llm_openai.py", line 94, in stream
    for chunk in openai.chat.completions.create(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 742, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/openai/_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/openai/_base_client.py", line 954, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/openai/_base_client.py", line 1014, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/openai/_base_client.py", line 1092, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/openai/_base_client.py", line 1014, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/openai/_base_client.py", line 1092, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/jay/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/openai/_base_client.py", line 1024, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
(venv) jay@jnetreloaded:~/Documents/Scripts/AI/gptme-ai$ 
</details>

**Comment by ErikBjare** [comment]
Looks like litellm has changed their default port, see https://github.com/ErikBjare/gptme/issues/175#issuecomment-2401459498
