### ISSUE TITLE
Error on windows 10

### ISSUE THREAD

**Issue by mastachef** [ErikBjare/gptme#203]
(base) C:\Users\Admin\Downloads\gptme\gptme>gptme
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\admin\.local\bin\gptme.exe\__main__.py", line 4, in <module>
  File "C:\Users\Admin\pipx\venvs\gptme\Lib\site-packages\gptme\__init__.py", line 2, in <module>
    from .cli import chat, main
  File "C:\Users\Admin\pipx\venvs\gptme\Lib\site-packages\gptme\cli.py", line 14, in <module>
    from .chat import chat
  File "C:\Users\Admin\pipx\venvs\gptme\Lib\site-packages\gptme\chat.py", line 7, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'

**Comment by mastachef** [comment]
(base) C:\Users\Admin\Downloads\gptme\gptme>gptme 'hello' -m local/nemotron-mini:4b
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\admin\.local\bin\gptme.exe\__main__.py", line 4, in <module>
  File "C:\Users\Admin\pipx\venvs\gptme\Lib\site-packages\gptme\__init__.py", line 2, in <module>
    from .cli import chat, main
  File "C:\Users\Admin\pipx\venvs\gptme\Lib\site-packages\gptme\cli.py", line 14, in <module>
    from .chat import chat
  File "C:\Users\Admin\pipx\venvs\gptme\Lib\site-packages\gptme\chat.py", line 7, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'

**Comment by ErikBjare** [comment]
Windows not supported, use WSL.
