### ISSUE TITLE
windows error

### ISSUE THREAD

**Issue by lgf5090** [ErikBjare/gptme#210]
Administrator in D:\04-program\deno
❯ gptme
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lgf50\.local\bin\gptme.exe\__main__.py", line 4, in <module>
  File "C:\Users\lgf50\pipx\venvs\gptme\Lib\site-packages\gptme\__init__.py", line 2, in <module>
    from .cli import chat, main
  File "C:\Users\lgf50\pipx\venvs\gptme\Lib\site-packages\gptme\cli.py", line 14, in <module>
    from .chat import chat
  File "C:\Users\lgf50\pipx\venvs\gptme\Lib\site-packages\gptme\chat.py", line 5, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

Administrator in D:\04-program\deno
❯ gptme.exe
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lgf50\.local\bin\gptme.exe\__main__.py", line 4, in <module>
  File "C:\Users\lgf50\pipx\venvs\gptme\Lib\site-packages\gptme\__init__.py", line 2, in <module>
    from .cli import chat, main
  File "C:\Users\lgf50\pipx\venvs\gptme\Lib\site-packages\gptme\cli.py", line 14, in <module>
    from .chat import chat
  File "C:\Users\lgf50\pipx\venvs\gptme\Lib\site-packages\gptme\chat.py", line 5, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'

**Comment by ErikBjare** [comment]
Windows is not supported, use WSL.

Please search for duplicates before reporting.
