### ISSUE TITLE
bug: gptme-server fails with `No module named 'flask'`

### ISSUE THREAD

**Issue by FilipHarald** [ErikBjare/gptme#290]
Perhaps this is an easy fix, but I didn't see anything for it in the docs.

```
$ gptme-server
Traceback (most recent call last):
  File "/home/filip/.local/bin/gptme-server", line 5, in <module>
    from gptme.server.cli import main
  File "/home/filip/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/gptme/server/__init__.py", line 5, in <module>
    from .api import create_app
  File "/home/filip/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/gptme/server/api.py", line 17, in <module>
    import flask
ModuleNotFoundError: No module named 'flask'
```

**Comment by ErikBjare** [comment]
You need to install it with the `server` extras (`pipx install gptme[server]`).

I see it is not mentioned in https://gptme.org/docs/server.html, will fix straight away.

**Comment by ErikBjare** [comment]
Fixed in https://github.com/ErikBjare/gptme/commit/cb561d6bbbb76649383e75ef176dab014eb9d50b
