### ISSUE TITLE
gptme-server fails with `TypeError: Client.__init__() got an unexpected keyword argument 'proxies'`

### ISSUE THREAD

**Issue by FilipHarald** [ErikBjare/gptme#291]
After successfully installing `gptme-server` I get an error when trying to start the server.

```
$ gptme-server --cors-origin='https://gptme.gptengineer.run'
[12:02:21] Using model: anthropic/claude-3-5-sonnet-20240620                                                                  
Traceback (most recent call last):
  File "/home/filip/.local/bin/gptme-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/filip/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/filip/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/filip/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/filip/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/filip/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/gptme/server/cli.py", line 50, in main
    init(
  File "/home/filip/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/gptme/init.py", line 60, in init
    init_llm(provider)
  File "/home/filip/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/gptme/llm/__init__.py", line 42, in init_llm
    init_anthropic(config)
  File "/home/filip/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/gptme/llm/llm_anthropic.py", line 33, in init
    anthropic = Anthropic(
                ^^^^^^^^^^
  File "/home/filip/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/anthropic/_client.py", line 122, in __init__
    super().__init__(
  File "/home/filip/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/anthropic/_base_client.py", line 856, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/filip/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/anthropic/_base_client.py", line 754, in __init__
    super().__init__(**kwargs)
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'
```

**Comment by ErikBjare** [comment]
I saw this earlier today: https://github.com/anthropics/anthropic-sdk-python/issues/766

Will update the library and make a new release, in the meantime you can do `pipx inject gptme httpx==0.27.2`

**Comment by ErikBjare** [comment]
Released https://github.com/ErikBjare/gptme/releases/tag/v0.24.1 with the fix

**Comment by FilipHarald** [comment]
> Released https://github.com/ErikBjare/gptme/releases/tag/v0.24.1 with the fix

I upgraded just now and it's working :+1: . Thanks!
