### ISSUE TITLE
`'?$'`, which is not a valid integer literal, hence the `ValueError`., kills the app

### ISSUE THREAD

**Issue by nslieske** [ErikBjare/gptme#43]
```bash
head -n 1000 gptme/gptme/tools/shell.py
```                                                                                                                                                       
```
Preview
$ head -n 1000 gptme/gptme/tools/shell.py                                                                                                              

 ⚠️ Execute code? (Y/n)  
import atexit
import os
import re
import select
import subprocess
import sys
from collections.abc import Generator

from ..message import Message
from ..util import ask_execute, print_preview


class ShellSession:
    def __init__(self) -> None:
        self.process = subprocess.Popen(
            ["bash"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            bufsize=0,  # Unbuffered
            universal_newlines=True,
        )
        self.stdout_fd = self.process.stdout.fileno()  # type: ignore
        self.stderr_fd = self.process.stderr.fileno()  # type: ignore

        # close on exit
        atexit.register(self.close)

        # set GIT_PAGER=cat
        self.run_command("export GIT_PAGER=cat")

    def run_command(self, command: str, output=True) -> tuple[int | None, str, str]:
        assert self.process.stdin

Traceback (most recent call last):
  File "/home/noah/.local/bin/gptme", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noah/.local/lib/python3.11/site-packages/gptme/cli.py", line 219, in main
    for msg in loop(log, no_confirm, model, stream=stream):  # pragma: no cover
  File "/home/noah/.local/lib/python3.11/site-packages/gptme/cli.py", line 271, in loop
    yield from execute_msg(msg_response, ask=not no_confirm)
  File "/home/noah/.local/lib/python3.11/site-packages/gptme/tools/__init__.py", line 29, in execute_msg
    yield from execute_codeblock(codeblock, ask)
  File "/home/noah/.local/lib/python3.11/site-packages/gptme/tools/__init__.py", line 42, in execute_codeblock
    yield from execute_shell(codeblock_content, ask=ask)
  File "/home/noah/.local/lib/python3.11/site-packages/gptme/tools/shell.py", line 116, in execute_shell
    returncode, stdout, stderr = shell.run_command(cmd)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noah/.local/lib/python3.11/site-packages/gptme/tools/shell.py", line 58, in run_command
    return_code = int(return_code_str)
                  ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '$?'
noah@n:~$ 
```

I'm not skilled enough to debug it on my own, sorry.
Analyzed the traceback:

```
Assistant: The traceback indicates that there is a `ValueError` being raised when the `gptme` application attempts to convert a string to an integer. The error occurs in the `run_command` method of the `shell.py` file, specifically at the line where it tries to convert the string `return_code_str` to an integer with the expression `int(return_code_str)`.

The string that is causing the error is `'?$'`, which is not a valid integer literal, hence the `ValueError`. It seems that the code is expecting a numeric return code from a shell command, but instead, it's getting a string that likely represents the last return code variable (`$?`) from the shell.

To resolve this issue, the code should be reviewed to ensure that it correctly captures the return code from the executed shell command. It's possible that the code is mistakenly capturing the string `'?$'` instead of the actual return code.

If you have access to the `shell.py` file and can modify it, you should look for the part of the code that sets `return_code_str` and ensure that it correctly captures the numeric return code from the shell command. If you need assistance with this, please let me know, and I can guide you through the process of debugging and fixing the code.                                                                                                              User:                   

i had it write a python script to read it and it came up with this

 The `shell.py` file defines a `ShellSession` class that manages a subprocess running a shell (bash in this case). It provides methods to run shell commands and capture their output and return code. Here's a summary of the key components:

- `ShellSession.__init__`: Initializes a `Popen` subprocess with `bash` and sets up pipes for `stdin`, `stdout`, and `stderr`. It also defines a delimiter to identify the end of command output.
- `ShellSession.run_command`: Takes a shell command as input, executes it, and captures the output and return code. It uses the delimiter to determine when the command output has ended.
- `ShellSession.close`: Closes the `stdin` of the subprocess and terminates it.
- `get_shell`: Returns a global instance of `ShellSession`, initializing it if it doesn't already exist.
- `set_shell`: Sets the global instance of `ShellSession`, used for testing.
- `execute_shell`: Takes a shell command as input, optionally asks for confirmation to execute, runs the command using `ShellSession.run_command`, and yields a `Message` with the command output.
- `_format_block_smart`: Formats the command output smartly, either as a single line or as a code block, depending on its length.
- `_shorten_stdout`: Shortens the command output to a specified number of lines, removing common prefixes and timestamps.

The `run_command` method is particularly important as it seems to be the source of the error you encountered. It constructs a command string that includes the original command and appends code to print the return code followed by a delimiter. After executing the command, it reads from the subprocess's `stdout` and `stderr`, looking for the delimiter and the "ReturnCode:" string to extract the return code.

The error you encountered (`ValueError: invalid literal for int() with base 10: '$?'`) suggests that the code is incorrectly capturing the string `'?$'` instead of the actual numeric return code. This could be due to a bug in how the output is parsed or how the return code is captured.

If you need to fix this issue, you would need to ensure that the `run_command` method correctly parses the return code from the command output. If you have access to modify the `shell.py` file, you could add additional logging or error handling around the return code parsing to diagnose the problem further.

**Comment by ErikBjare** [comment]
This should happen very rarely. Not exactly sure why it happens sometimes.

I fixed so that the error is handled more gracefully in https://github.com/ErikBjare/gptme/commit/becab4d69a85f2c769f610f6200de44c7fabdcaf

Closing for now, if this is a recurring issue for you, please let me know! Thanks for reporting :)
