### ISSUE TITLE
Error on Windows: `KeyError: 'USER'`

### ISSUE THREAD

**Issue by dillfrescott** [ErikBjare/gptme#5]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\micro\miniconda3\Scripts\gptme.exe\__main__.py", line 4, in <module>
  File "C:\Users\micro\miniconda3\Lib\site-packages\gptme\cli.py", line 40, in <module>
    from .logmanager import LogManager, print_log
  File "C:\Users\micro\miniconda3\Lib\site-packages\gptme\logmanager.py", line 12, in <module>
    from .prompts import initial_prompt
  File "C:\Users\micro\miniconda3\Lib\site-packages\gptme\prompts.py", line 7, in <module>
    USER = os.environ["USER"]
           ~~~~~~~~~~^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'USER'
```

**Comment by karvla** [comment]
This particular error could be fixed by using `os.getenv("USER", "")` instead of `os.env["USER"]`.

But other issues would likely arise downstream when using Windows since the all prompts etc states that bash is to be used. 

The best solution would probably be to avoid using Windows for now (or to use [WSL](https://learn.microsoft.com/en-us/windows/wsl/install)).

**Comment by ErikBjare** [comment]
Yeah, I'm not going to bother thinking about Windows support for now.

I'd be happy to accept PRs from Windows users though, as long as it doesn't get too messy. But you should probably use WSL as @karvla suggested.

Thanks for filing the issue.

**Comment by jreoka** [comment]
Okay! Thanks for the responses!
